### ISSUE TITLE
Trademark conflict with Apache Taverna?

### ISSUE THREAD

**Issue by stain** [teamtaverna/taverna#6]
You may want to reconsider using the name "Taverna" for your open source software, as [Apache Taverna](https://taverna.incubator.apache.org/) is a trademark of the [Apache Software Foundation](http://apache.org/) - and [has been an open source project since 2003](https://en.wikipedia.org/wiki/Apache_Taverna).

See also https://www.apache.org/foundation/marks/

**Comment by kosyfrances** [comment]
Thank you for letting us know @stain. We are going to use a different name for our project.
